name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm run test

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
    - name: Build Readme
      run: npm run docs

    - name: Build Data
      run: npm run convert

    - name: Update Readme
      uses: test-room-7/action-update-file@v1
      with:
        file-path: README.md
        commit-msg: Update Readme
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy README file to "profile"
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'README.md'
        destination_repo: 'robkostermans/robkostermans'
        destination_folder: '/'
        user_email: 'robkostermans@gmail.com'
        user_name: 'robkostermans'
        commit_message: 'Update from action'

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build